---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd

  labels:
    environment: local
    purpose: cont-delivery

spec:
  project: argo-projects

  revisionHistoryLimit: 3

  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 5.13.1
    helm:
      values: |
        extraObjects: []

        global:
          logging:
            format: json

        configs:
          cm:
            exec.enabled: false

          params:
            server.enable.gzip: true

          styles: |
            .sidebar {
              background: linear-gradient(#e66465, #9198e5);
            }
            .nav-bar {
              background: linear-gradient(to bottom, #999, #777, #333, #222, #111);
            }


  destination:
    name: in-cluster
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
