---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: argo-cd-backup
  namespace: argocd
spec:
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 5
      template:
        spec:
		  containers:
			- name: argo-cd-backup
			  image: 
			  command: [ "argocd" ]
			  args: [ "admin" "export" "--auth-token" "token" ">" "backup" ]
