---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd

  labels:
    environment: local
    purpose: cont-delivery

spec:
  project: argo-projects

  revisionHistoryLimit: 3

  sources:
  - repoURL: git@github.com:CouchPartyGames/multiplayer-service-demo.git
    targetRevision: main
    ref: myRepo
  - chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 5.16.9
    helm:
      valueFiles:
        - $myRepo/helm/external-values/argocd-local.yaml


  destination:
    name: in-cluster
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
