---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argo-projects
  namespace: argocd

  labels:
    environment: local
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: Kubernetes Deployment

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - https://argoproj.github.io/argo-helm
  - 'git@github.com:CouchPartyGames/multiplayer-service-demo.git'

  destinations:
  - namespace: argocd
    name: in-cluster

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
