---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agones-local
  namespace: argocd

  labels:
    environment: local
spec:
  project: hosting-local

  sources:
  - repoURL: git@github.com:CouchPartyGames/multiplayer-service-demo.git
    targetRevision: main 
    ref: myRepo
  - repoURL: https://agones.dev/chart/stable
    chart: agones
    targetRevision: 1.31.0
    helm:
      valueFiles:
      - $myRepo/agones-local.yaml

  destination:
    name: in-cluster
    namespace: agones-system

  syncPolicy:
    #automated: {}
      #prune: true
      #selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 3
      backoff:
        duration: 15s

  revisionHistoryLimit: 3
