---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hosting-local
  namespace: argocd

  labels:
    environment: local
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Dedicated Game Hosting for Local Environment

  sourceRepos:
  - 'https://agones.dev/chart/stable'
  - 'git@github.com:CouchPartyGames/multiplayer-service-demo.git'

  destinations:
  - namespace: agones-system
    name: in-cluster
  - namespace: default
    name: in-cluster
  - namespace: kube-system
    name: in-cluster
  - namespace: '*'			# allow games to be hosted in any namespace, argocd needs access
    name: '*'

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
