---
# https://cert-manager.io/docs/installation/helm/

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd

  labels:
    environment: local
    purpose: certificates

spec:
  project: default

  sources:
  - repoURL: git@github.com:CouchPartyGames/multiplayer-service-demo.git
    targetRevision: main 
    ref: myRepo
  - repoURL: https://charts.jetstack.io
    targetRevision: v1.11.0
    chart: cert-manager
    helm:
      valueFiles: 
      - $myRepo/helm/external-values/local/cert-manager-local.yaml

  destination:
    name: in-cluster
    namespace: cert-manager

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
