---
# https://cert-manager.io/docs/usage/certificate/

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: allocator-certificate
  namespace: agones-system
spec:
  commonName: 127.0.0.1
  ipAddresses:
    - 127.0.0.1
  secretName: allocator-tls
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
