---
# https://cert-manager.io/docs/installation/helm/

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd


  #finalizers:
  #  - resources-finalizer.argocd.argoproj.io
  labels:
    environment: local
    purpose: certificates

spec:
  project: default

  source:
    repoURL: https://charts.jetstack.io
    targetRevision: v1.10.1
    chart: cert-manager
    helm:
      values: |
        prometheus:
          enabled: false
        webhook:
          timeout: 30
        installCRDs: true

  destination:
    name: in-cluster
    namespace: cert-manager

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true

