---
# https://github.com/fluent/helm-charts

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd


  #finalizers:
  #  - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  sources:
  - repoURL: git@github.com:CouchPartyGames/multiplayer-service-demo.git
    targetRevision: main 
    ref: myRepo
  - repoURL: https://fluent.github.io/helm-charts
    targetRevision: 0.46.0
    chart: fluent-bit
    helm:
      valueFiles:
      - $myRepo/helm/external-values/local/fluent-bit-local.yaml

  destination:
    name: in-cluster
    namespace: logging
    

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true

