---
# https://cert-manager.io/docs/installation/helm/

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd

  labels:
    environment: local
    purpose: identity

spec:
  project: default

  sources:
  - repoURL: git@github.com:CouchPartyGames/multiplayer-service-demo.git
    targetRevision: main 
    ref: myRepo
  - repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 13.0.0 
    chart: keycloak
    helm:
      valueFiles:
      - $myRepo/helm/external-values/keycloak-local.yaml

  destination:
    name: in-cluster
    namespace: cert-manager

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
