---
#

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd

  labels:
    environment: local
    purpose: certificates

spec:
  project: default

  sources:
  - repoURL: git@github.com:CouchPartyGames/multiplayer-service-demo.git
    targetRevision: main 
    ref: myRepo
  - repoURL: https://codecentric.github.io/helm-charts
    targetRevision: 5.2.2
    chart: mailhog
    helm:
      valueFiles: 
      - $myRepo/helm/external-values/local/mailhog-local.yaml

  destination:
    name: in-cluster
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
