---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postfix
  namespace: argocd

  labels:
    environment: local
    purpose: mail

spec:
  project: default

  sources:
  - repoURL: git@github.com:CouchPartyGames/multiplayer-service-demo.git
    targetRevision: main 
    ref: myRepo
  - repoURL: https://bokysan.github.io/docker-postfix/
    targetRevision: 3.5.1
    chart: mail
    helm:
      valueFiles: 
      - $myRepo/helm/external-values/local/postfix-local.yaml

  destination:
    name: in-cluster
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
