---
# https://github.com/prometheus-community/helm-charts

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd


spec:
  project: default

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 25.18.0
    chart: prometheus
    helm:
      values: |
        prometheus:
          enabled: false
        webhook:
          timeout: 30

  destination:
    name: in-cluster
    namespace: monitoring
    

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-crds
  namespace: argocd


spec:
  project: default

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 10.0.0
    chart: prometheus-operator-crds
    helm:
      values: |
        prometheus:
          enabled: false
        webhook:
          timeout: 30

  destination:
    name: in-cluster
    namespace: monitoring
    

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true

