---
# https://github.com/prometheus-community/helm-charts

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd


spec:
  project: default

  source:
    repoURL: https://charts.jetstack.io
    targetRevision: v1.10.0
    chart: cert-manager
    helm:
      values: |
        prometheus:
          enabled: false
        webhook:
          timeout: 30

  destination:
    name: local
    namespace: monitoring
    

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

