---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: agones-appset
  namespace: argocd

  labels:
    environment: local
spec:
  generators:
  - list: 
      # Parameters are generated based on this cluster list, to be substituted
      # into the template below.
      elements: 
      - cluster: "in-cluster"
        region: "local"
        version: "1.25.0"
  template:
    metadata:
      name: 'agones-{{region}}'

      labels:
        region: '{{region}}'
        environment: local
    spec:
      project: hosting-local

      source:
        chart: agones
        repoURL: https://agones.dev/chart/stable
        targetRevision: '{{version}}'
        helm:
          parameters:
            - name: "agones.ping.install"
              value: "false"
        # >= ArgoCD 2.5 
        #externalValueFiles:
        #- repoURL: 'git@bitbucket.org:repo3/path.git'
        #  targetRevision: main
        #  valueFiles:
        #    - values.yaml

      destination:
        name: '{{cluster}}'
        namespace: agones-system

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
        retry:
          limit: 3
          backoff:
            duration: 15s
