---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: open-match-appset
  namespace: argocd

  labels:
    environment: local
spec:
  generators:
  - list: 
      elements: 
      - cluster: https://kubernetes.default.svc
        region: "local"
        version: "1.3.0"
  template:
    metadata:
      name: 'open-match-{{region}}'
      labels:
        region: '{{region}}'
        environment: local
    spec:
      project: matchmaking-local

      source:
        chart: open-match
        repoURL: https://open-match.dev/chart/stable
        targetRevision: '{{version}}'

      destination:
        server: '{{cluster}}'
        namespace: open-match

      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
        retry:
          limit: 3
