---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd

  labels:
    environment: local
    purpose: proxy

spec:
  project: authentication

  sources:
  - repoURL: git@github.com:CouchPartyGames/multiplayer-service-demo.git
    targetRevision: main 
    ref: myRepo
  - repoURL: https://codecentric.github.io/helm-charts
    targetRevision: 4.4.2
    chart: ingress-nginx
    helm:
      valueFiles:
      - $myRepo/helm/external-values/local/ingress-nginx-local.yaml

  destination:
    name: in-cluster
    namespace: keycloak

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
