---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd

  labels:
    environment: local
    purpose: identity


spec:
  project: authentication

  sources:
  - repoURL: git@github.com:CouchPartyGames/multiplayer-service-demo.git
    targetRevision: main 
    ref: myRepo
  - repoURL: https://jp-gouin.github.io/helm-openldap/
    targetRevision: 4.0.2
    chart: openldap-stack-ha
    helm:
      valueFiles:
      - $myRepo/helm/external-values/local/openldap-ha-local.yaml
