---
# 

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd

  labels:
    environment: local
    purpose: database

spec:
  project: authentication

  sources:
  - repoURL: git@github.com:CouchPartyGames/multiplayer-service-demo.git
    targetRevision: main 
    ref: myRepo
  - repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.1.6
    chart: postgresql
    helm:
      valueFiles:
      - $myRepo/helm/external-values/local/postgresql-local.yaml

  destination:
    name: in-cluster
    namespace: keycloak

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
