---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: authentication
  namespace: argocd

  labels:
    environment: local
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Authenticate Users for local environments

  sourceRepos:
  - 'https://codecentric.github.io/helm-charts'
  - 'git@github.com:CouchPartyGames/multiplayer-service-demo.git'
  - 'https://charts.bitnami.com/bitnami'

  destinations:
  - namespace: keycloak
    name: in-cluster

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
