---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd

  labels:
    environment: local
    purpose: docker-registry
    region: local

spec:
  project: harbor

  revisionHistoryLimit: 3

  source:
    chart: harbor
    repoURL: https://helm.goharbor.io
    targetRevision: 1.10.3
    #helm:
    #  values: |
    #    extraObjects: []


  destination:
    name: in-cluster
    namespace: default

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
