---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd

  labels:
    environment: local
    purpose: database

spec:
  project: postgresql-ha

  revisionHistoryLimit: 3

  source:
    chart: postgresql-ha
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 9.4.5

  destination:
    name: in-cluster
    namespace: default

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
