---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: harbor
  namespace: argocd

  labels:
    environment: local
    purpose: docker-registry
    region: local

  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  
  description: High Availability, Multi-Tenant Docker Registry

  sourceRepos:
  - https://helm.goharbor.io
  - https://charts.bitnami.com/bitnami

  destinations:
  - namespace: default
    name: in-cluster

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
