---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd

  labels:
    environment: local
    purpose: redis-sential
    region: local

spec:
  project: harbor

  revisionHistoryLimit: 3

  source:
    chart: redis
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 17.2.0

  destination:
    name: in-cluster
    namespace: default

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
