---
# Example Dedicated Game using Agones
#
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: marble-madness
  namespace: argocd

  #finalizers:
  #  - resources-finalizer.argocd.argoproj.io

  labels:
    name: marble-madness
    region: local
    environment: local
spec:

  project: games

  revisionHistoryLimit: 4

  source:
    repoURL: https://couchpartygames.github.io/fleet
    targetRevision: 1.0.9
    chart: fleet
    helm:
      values: |
        fleet:
          name: "simple-game-server"
          replicas: 1
          labels:
            game-version: 0.13
            region: local
            environment: local


        gameServer:
          container:
            - name: "simple"
              image: gcr.io/agones-images/simple-game-server
              tag: 0.13
              port:
                containerPort: 7654
                protocol: UDP
              resources:
                requests:
                  memory: 125Mi
                  cpu: 100m
                limits:
                  memory: 512Mi
                  cpu: 500m

  
      #externalValueFiles:
      #  - repoURL: 'git@bitbucket.org:repo3/path.git'
      #    targetRevision: main
      #    valueFiles:
      #      - games/marble-madness/fleet.yaml
      #      - games/marble-madness/secrets.yaml

  destination:
    name: in-cluster
    namespace: marble-madness

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 15s
        maxDuration: 2m
