---
# Example Dedicated Game using Agones
#
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-game-server
  namespace: argocd

  #finalizers:
  #  - resources-finalizer.argocd.argoproj.io

  labels:
    game-name: "simple-game-server"
    game-version: "0.13"
    game-company: "CouchPartyGames"
    region: local
    environment: local

spec:

  project: games

  revisionHistoryLimit: 4

  source:
    repoURL: https://couchpartygames.github.io/cpg-helm
    targetRevision: 1.0.9
    chart: fleet
  sources:
    - repoURL: git@github.com:CouchPartyGames/multiplayer-service-demo.git
      targetRevision: main
      path: helm/external-values
      helm:
        valueFiles:
        - simple-game-local.yaml


  destination:
    name: in-cluster
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 15s
        maxDuration: 2m
