
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: harbor
  namespace: argocd

  labels:
    environment: local
    purpose: docker-registry

  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: Docker Registry

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - https://helm.goharbor.io

  destinations:
  - namespace: argocd
    name: in-cluster

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
