# https://github.com/fluent/helm-charts/blob/main/charts/fluent-bit/values.yaml
# https://docs.fluentbit.io/manual/administration/configuring-fluent-bit

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: /metrics
  prometheus.io/port: "2021"

config:
  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        multiline.parser docker, cri
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On

    [INPUT]
        name            fluentbit_metrics
        tag             internal_metrics
        scrape_interval 2


  outputs: |
    [OUTPUT]
        Name        stdout
        Match       *

    [OUTPUT]
        name        loki
        match       host.* kube.*
        host        loki-write
        port        3100
        tenant_id   1

    [OUTPUT]
        name            prometheus_exporter
        match           internal_metrics
        host            0.0.0.0
        port            2021


logLevel: info
