# helm show values bitnami/keycloak
#
# https://artifacthub.io/packages/helm/bitnami/keycloak

global:
  storageClass: ""


extraDeploy: []

auth:
  adminPassword: "password"
  # Secret
  #existingSecret: "keycloak"
  # Key to find password from the Secret
  #passwordSecretKey: "admin-password"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 11


service:
  type: ClusterIP
  http:
    enable: true


ingress:
  enabled: false


postgresql:
  enabled: true
  auth:
    postgresPassword: password
    password: bn-password
    database: keycloak

