# helm show values bitnami/keycloak
#
# https://artifacthub.io/packages/helm/bitnami/keycloak





auth:
  adminUser: "admin"
  existingSecret: "keycloak-admin-password"
  passwordSecretKey: "password"

production: false

proxy: edge

extraDeploy:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: keycloak-admin-password
    data:
      password: dmFsdWUtMg0KDQo=

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5

dbchecker:
  enabled: true

database:
  vendor: postgres
  hostname: postgresql.keycloak.svc.cluster.local
  port: 5432
  username: keycloak
  password: keycloak
  database: bitnami_keycloak

metrics:
  enabled: false


# https://artifacthub.io/packages/helm/bitnami/keycloak#keycloak-statefulset-parameters
replicas: 1

     
#initContainers:
#  - name: custom-themes
#    image: <your-image>
#    command: [ "sh", "-c", "cp -vR /keycloak/themes/* /themes" ]
#    volumeMounts:
#      - name: custom-themes
#        mountPoint: /themes 
#  - name: custom-extensions
#    image: ghcr.io/couchpartygames/
#    command: [ "sh", "-c", "cp -vR /keycloak/extensions/* /extensions" ]
#    volumeMounts:
#      - name: custom-extensions
#        mountPoint: /extensions

extraVolumes:
  - name: custom-themes
    emptyDir: {}
  - name: custom-extensions
    emptyDir: {}

extraVolumeMounts:
  - name: custom-themes
    mountPath: /opt/bitnami/keycloak/themes
    emptyDir: {}

cache:
  # Development environment should be set to false
  enabled: false

logging:
  output: json
  level: INFO
