# helm show values bitnami/keycloak
#
# https://artifacthub.io/packages/helm/bitnami/keycloak

replicas: 1


autoscaling:
  enabled: false

command:
  - "/opt/keycloak/bin/kc.sh"
  - "start"
  - "--http-enabled=true"
  - "--http-port=8080"
  - "--hostname-strict=false"
  - "--hostname-strict-https=false"

extraEnv: |
  - name: KEYCLOAK_ADMIN
    value: admin
  - name: KEYCLOAK_ADMIN_PASSWORD
    value: "admin"


#  - name: KEYCLOAK_ADMIN_PASSWORD
#    valueFrom:
#      secretKeyRef:
#        name: keycloak-admin-password
#        key: password

dbchecker:
  enabled: true

database:
  vendor: postgres
  hostname: postgresql.keycloak.svc.cluster.local
  port: 5432
  username: keycloak
  password: keycloak
  database: keycloak

metrics:
  enabled: false
