# helm show values bitnami/keycloak
#
# https://artifacthub.io/packages/helm/bitnami/keycloak

global:
  storageClass: ""


extraDeploy: []


auth:
  # Keycloak Admin user
  adminUser: "user@user.com"
  # Keycloak Admin Password
  adminPassword: "pass123"


extraEnvVars: []
  #- name: JGROUPS_DISCOVERY_PROTOCOL
    #key: dns.DNS_PING

tls:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 11


service:
  type: ClusterIP
  http:
    enable: true


ingress:
  enabled: false

networkPolicy:
  enabled: false

postgresql:
  enabled: true
  auth:
    # Password for the "postgres" admin user
    postgresPassword: "admin-pw"
    username: "keycloak"
    password: "keycloak-pw"
    database: "keycloak"

logging:
  output: json
  level: INFO
