# helm show values bitnami/keycloak
#
# https://artifacthub.io/packages/helm/bitnami/keycloak


auth:
  adminUser: "admin"
  existingSecret: "keycloak-admin-password"
  passwordSecretKey: "password"

production: false

proxy: edge

extraDeploy:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: keycloak-admin-password
    data:
      password: cGFydHk=

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5

dbchecker:
  enabled: true

database:
  vendor: postgres
  hostname: postgresql.keycloak.svc.cluster.local
  port: 5432
  username: keycloak
  password: party
  database: keycloak

metrics:
  enabled: false


# https://artifacthub.io/packages/helm/bitnami/keycloak#keycloak-statefulset-parameters
replicas: 1

initdbScripts:
  add-providers-themes.sh: |
    #!/bin/bash
    echo "Installing Themes/Providers"
    cp -v /providers/*.jar /opt/bitnami/keycloak/providers
     
initContainers:
  - name: custom-providers
    image: ghcr.io/couchpartygames/keycloak-extras:0.0.5
    command: [ "sh", "-c", "cp -v /keycloak/providers/*.jar /providers 2> /dev/null || : " ]
    volumeMounts:
      - name: custom-providers
        mountPath: /providers

extraVolumes:
  - name: custom-providers
    emptyDir: {}

extraVolumeMounts:
  - name: custom-providers
    mountPath: /providers

cache:
  # Development environment should be set to false
  enabled: false

logging:
  output: json
  level: INFO
