auth:
  adminUser: admin
  adminPassword: admin

#image:
#  pullSecrets:
#    - docker-registry

#initContainers:
#  - name: custom-themes
#    image: <your-image>
#    command: [ "sh", "-c", "cp -vR /keycloak/themes/* /themes" ]
#    volumeMounts:
#      - name: custom-themes
#        mountPoint: /themes

extraVolumes:
  - name: custom-themes
    emptyDir: {}

extraVolumeMounts:
  - name: custom-themes
    mountPath: /opt/bitnami/keycloak/themes
    emptyDir: {}


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5

service:
  type: ClusterIP


cache:
  # Development environment should be set to false
  enabled: false

logging:
  output: json
  level: INFO
