# helm show values bitnami/keycloak
#
# https://artifacthub.io/packages/helm/bitnami/keycloak

global:
  storageClass: ""


extraDeploy: []

auth:
  adminUser: "user"
  adminPassword: "password"
  # Secret
  #existingSecret: "keycloak"
  # Key to find password from the Secret
  #passwordSecretKey: "admin-password"


tls:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 11


service:
  type: ClusterIP
  http:
    enable: true


ingress:
  enabled: false

networkPolicy:
  enabled: false

postgresql:
  enabled: true
  auth:
    postgresPassword: "password"
    username: "keycloak"
    password: "bn-password"
    database: "keycloak"

logging:
  output: json
  level: DEBUG
