# helm show values bitnami/keycloak

auth:
  adminPassword: "password"
  # Secret
  #existingSecret: "keycloak"
  # Key to find password from the Secret
  #passwordSecretKey: "admin-password"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 11
