# 

global:
  postgresql:
    auth:
      # Password for the "postgres" admin user 
      postgresPassword: pgpass

      # custom user
      username: keycloak
      password: keycloak
      database: bitnami_keycloak



image:
  registry: docker.io
  repository: bitnami/postgresql
  tag: 15.1.0-debian-11-r12


auth:
  enablePostgresUser: true
