---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: agones-appset
  namespace: argocd
spec:
  generators:
  - list: 
      # Parameters are generated based on this cluster list, to be substituted
      # into the template below.
      elements: 
      - cluster: "in-cluster"
        region: "us-east"
        provider: "gcp"
  template:
    metadata:
      name: 'agones-{{region}}'
      labels:
        region: {{region}}
        provider: {{provider}}
        env: prod
    spec:
      project: agones-prod

      source:
        chart: agones
        repoURL: https://agones.dev/chart/stable
        targetRevision: 1.24.0

      destination:
        name: '{{cluster}}'
        namespace: agones-system

      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
        retry:
          limit: 3
