---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: open-match-appset
spec:
  generators:
  - list:
      elements:
      - region: us-east
        provider: gcp
        cluster: gcp-us_east
  template:
    metadata:
      name: 'open-match-{{ region }}'
      labels:
        region: {{ region }}
        provider: {{ provider }}
    spec:
      project: infra

      source:
        chart: open-match
        repoURL: https://open-match.dev/chart/stable
        targetRevision: 1.3.0

      destination:
        name: '{{cluster}}'
        namespace: guestbook

      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
        retry:
          limit: 3
