---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-match-local
  namespace: argocd

  labels:
    environment: local
spec:
  project: matchmaking-local

  sources:
  - repoURL: git@github.com:CouchPartyGames/multiplayer-service-demo.git
    targetRevision: main 
    ref: myRepo
  - chart: open-match-components
    repoURL: https://couchpartygames.github.io/helm-charts
    targetRevision: 0.0.3
    helm:
      valueFiles:
      - $myRepo/helm/external-values/open-match-components-local.yaml

  destination:
    name: in-cluster
    namespace: open-match

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 3
