---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: matchmaking-local
  namespace: argocd

  labels:
    environment: local

  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Game Matchmaking Service for Local Environment

  sourceRepos:
  - 'https://open-match.dev/chart/stable'

  destinations:
  - namespace: open-match
    name: in-cluster
  #- namespace: kube-system
  #  server: https://kubernetes.default.svc
  #- namespace: default
  #  server: https://kubernetes.default.svc

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
