# https://github.com/googleforgames/agones/blob/main/install/helm/agones/values.yaml
# https://agones.dev/site/docs/installation/install-agones/helm/

agones:
  
  # https://agones.dev/site/docs/guides/feature-stages/#feature-gates
  featureGates: "PlayerTracking=true"
  
  crds:
    install: true
    cleanupOnDelete: true
    cleanupJobTTL: 60

  metrics:
    prometheusEnabled: true
    prometheusServiceDiscovery: true
    serviceMonitor:
      enabled: true
      interval: 30s
      
  controller:
    replicas: 1
    generateTLS: false
    logLevel: info
    annotations:
      region: local
      provider: minikube
    
  ping:
    install: false
    replicas: 1
    http:
      annotations:
        region: local
        provider: minikube
    udp:
      annotations:
        region: local
        provider: minikube

  allocator:
    replicas: 1
    generateTLS: false
    generateClientTLS: false
    annotations:
      region: local
      provider: minikube

  extensions:
    replicas: 1
    logLevel: info
    annotations:
      region: local
      provider: minikube

gameservers:
  namespaces:
  - default
  minPort: 6000
  maxPort: 8000


# https://agones.dev/site/docs/installation/install-agones/helm/#helm-installation
helm:
  installTests: false
