# https://github.com/googleforgames/agones/blob/main/install/helm/agones/values.yaml
# https://agones.dev/site/docs/installation/install-agones/helm/

agones:

  # https://agones.dev/site/docs/guides/feature-stages/#feature-gates
  featureGates: "PlayerTracking=true"
  
  crds:
    install: true
    cleanupOnDelete: true
    cleanupJobTTL: 60
    
  metrics:
    prometheusEnabled: true
    prometheusServiceDiscovery: true
    serviceMonitor:
      enabled: true
      interval: 30s
      
  controller:
    generateTLS: false
    logLevel: info

  ping:
    install: true
    replicas: 2
    http:
      annotations:
        region: us-east-1
        provider: aws
    udp:
      annotations:
        region: us-east-1
        provider: aws
        
  allocator:
    generateTLS: false
    generateClientTLS: false
    annotations:
      region: us-east-1
      provider: aws

  extensions:
    logLevel: info


gameservers:
  namespaces:
    - default
    - xbox
    - linux
  minPort: 5000
  maxPort: 9000
  
# https://agones.dev/site/docs/installation/install-agones/helm/#helm-installation
helm:
  installTests: false
