redis-ha:
  enable: true


controller:
  enableStatefulSet: true
  metrics:
    enabled: true


server:
  autoscaling:
    enabled: true
    minReplicas: 2
  metrics:
    enabled: true
  rbacConfig:
    policy.csv: |
      p, role:automate-role, clusters, create, * , allow
      p, role:automate-role, clusters, get, * , allow
      p, role:automate-role, clusters, delete, * , allow
      p, role:automate-role, applications, *, */*, allow
      g, automated, role:automate-role

  config:
    url: https://argocd.example.com
    helm.valuesFileSchemes: secrets, https, secrets+gpg-import, secrets+gpg-import-kubernetes

    accounts.automated: apiKey

    kustomize.buildOptions: --enable-alpha-plugins


repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2
  metrics:
    enabled:


applicationSet:
  enabled: true

notifications:
  enabled: true
  metrics:
    enabled: true


configs:
  #gpgKeys:
  #  id: |
  #    -----BEGIN PGP PUBLIC KEY BLOCK-----
  #    -----END PGP PUBLIC KEY BLOCK-----
  repositories:
    couchpartygames-github:
      url: https://github.com/CouchPartyGames/fleet
  styles: ".nav-bar { background: linear-gradient(#e66465, #9198e5); }"
