crds:
  install: false

extraObjects: []

global:
  image:
    tag: v2.6.0-rc1
  logging:
    format: json

configs:
  cm:
    exec.enabled: false
    url: 'localhost'

  params:
    server.enable.gzip: true

  styles: |
    .sidebar {
      background: linear-gradient(#e66465, #9198e5);
    }
    .nav-bar {
      background: linear-gradient(to bottom, #999, #777, #333, #222, #111);
    }
