# open match

global:
  telemetry:
    jaeger:
      enabled: true

open-match-override:
  enable: "true"


open-match-core:

  # kubectl port-forward --namespace open-match service/om-swaggerui 51500:51500
  swaggerui:
    enabled: true

