# open match
# https://github.com/googleforgames/open-match/blob/main/install/helm/open-match/values.yaml
# https://github.com/googleforgames/open-match/blob/main/install/helm/open-match/values-production.yaml
# https://openmatch.dev/site/docs/installation/helm/#configuration

global:
  telemetry:
    jaeger:
      enabled: true
    prometheus:
      enabled: false
      serviceDiscovery: false
    grafana:
      enabled: false
    stackdriverMetrics:
      enabled: false
    reportingPeriod: 1m
    
  logging:
    rpc:
      enabled: true
      
  tls:
    enabled: false



open-match-core:
  enabled: true
  # kubectl port-forward --namespace open-match service/om-swaggerui 51500:51500
  swaggerui:
    enabled: false


open-match-override:
  enable: true

open-match-telemetry:
  enabled: true

open-match-scale:
  enabled: true
